# Generated by Django 3.2.8 on 2023-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230509_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='author',
        ),
        migrations.AddField(
            model_name='jobs',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='employer',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
