# Generated by Django 3.2.8 on 2023-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230518_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='require',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='wage',
            field=models.IntegerField(default=0),
        ),
    ]
