# Generated by Django 3.2.8 on 2023-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230518_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='wage',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
