# Generated by Django 3.2.8 on 2023-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_jobs_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='academic',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
