# Generated by Django 3.2.8 on 2023-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230520_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='kind',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.URLField(blank=True, default='https://pic.616pic.com/ys_img/00/04/60/DToXBfxigM.jpg', max_length=256, null=True),
        ),
    ]
