# Generated by Django 3.2.8 on 2023-05-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airdata',
            options={'managed': True},
        ),
    ]
