# Generated by Django 3.2.8 on 2023-09-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_jobs'),
    ]

    operations = [
    ]
